### PR TITLE
I AM TIRED LEAVE ME ALONE PLEASEEE

### PR DESCRIPTION
**Pull request by Samma2009**

### CODE REVIEW

**Comment by SzymekkYT** [comment]
GET BACK TO WORK

**Comment by Samma2009** [comment]
just see how many things i added

**Comment by Samma2009** [comment]
> GET BACK TO WORK

ok boss

**Comment by SzymekkYT** [comment]
_[yes](https://youtu.be/ioszPQAtiPk?si=VVkKpXm8Dx96h9on)_

**Pull request merged**
